jobs:
  include:
    - language: python
      python: 3.9
      before_install: cd server
      install: make bootstrap
      script: make
    - language: node_js
      node_js: 14
      before_install: cd client
      install: npm i
      script: npm run lint