version: "3.8"
services:
  server:
    container_name: server
    image: python:3.9.1
    ports:
      - 5000:5000
    working_dir: /uwt
    build: ./server
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: uwt
      DB_PASS: uwt-pw
    volumes:
      - ./server:/uwt
    command: python api.py
    links:
      - db
  db:
    container_name: db
    image: mongo:4.4.3-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uwt
      MONGO_INITDB_ROOT_PASSWORD: uwt-pw
    volumes:
      - ./docker/mongodb/entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - /data/db
    ports:
      - 27017:27017
    command: mongod --auth
    logging:
      driver: none