version: "3.8"
services:
  api:
    container_name: api
    image: python:latest
    ports:
      - 5000:5000
    working_dir: /uwt
    build: ./server
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 27017
    volumes:
      - .:/uwt
    command: python server/api.py
    links:
      - db
  db:
    container_name: db
    image: mongo:latest
    restart: always
    volumes:
      - ./docker/mongodb/entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - /data/db
    ports:
      - 27017:27017